%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-ros2-snapshot
Version:        0.0.7
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ros2_snapshot package

License:        Apache-2.0
URL:            https://index.ros.org/p/ros2_snapshot/#kilted
Source0:        %{name}-%{version}.tar.gz

Requires:       graphviz
Requires:       python%{python3_pkgversion}-psutil
Requires:       python%{python3_pkgversion}-yaml
Requires:       python3-pydantic
Requires:       python3-pygraphviz
Requires:       ros-kilted-ament-index-python
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros2cli
Requires:       ros-kilted-ros2component
Requires:       ros-kilted-ros2node
Requires:       ros-kilted-ros2param
Requires:       ros-kilted-ros2pkg
Requires:       ros-kilted-ros2service
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-demo-nodes-py
%endif

%description
ROS2 Snapshot - contains workspace modeler and snapshot tools

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Wed Apr 29 2026 CNU Robotics CHRISLab <robotics@cnu.edu> - 0.0.7-1
- Autogenerated by Bloom

* Sat Feb 21 2026 CNU Robotics CHRISLab <robotics@cnu.edu> - 0.0.2-1
- Autogenerated by Bloom

